# Generated by Django 3.0 on 2019-12-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191215_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='locations',
            field=models.ManyToManyField(to='api.Location'),
        ),
    ]
